module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'root',
        'api',
        'web',
        'shared',
        'docker',
        'auth',
        'tenants',
        'users',
        'roles',
        'permissions',
        'parliamentarians',
        'emendas',
        'siop',
        'impediments',
        'convenios',
        'financial-schedule',
        'physical-execution',
        'accountability',
        'documents',
        'alerts',
        'dashboards',
        'reports',
        'audit-logs',
        'integrations',
        'public-api',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'body-max-line-length': [1, 'always', 100],
  },
};
